export const GET_ALL_COUNTRIES_DATA = 'GET_ALL_COUNTRIES_DATA';
export const FILTER_COUNTRIES = 'FILTER_COUNTRIES';
export const CLEAR_FILTER_COUNTRIES = 'CLEAR_FILTER_COUNTRIES';
export const SET_LOADING = 'SET_LOADING';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
